import { Consultant } from './consultant';

export const CONSULTANT: Consultant[] = [
  { id: 1, lastname: 'Andalib', firstname: 'Mr. Nice', email: 'acodd@yopmail.com', phoneNumber: 784126978 },
  { id: 2, lastname: 'Andaliba', firstname: 'Mr. Nicea', email: 'urrab@yopmail.com', phoneNumber: 7841269728 },
  { id: 3, lastname: 'Andalibx', firstname: 'Camille', email: 'orrip@yopmail.com', phoneNumber: 784126978 },
  { id: 4, lastname: 'Andalibaw', firstname: 'Naruto', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 5, lastname: 'Andalibad', firstname: 'Keltoum', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 6, lastname: 'Andalsad', firstname: 'Mr. Nice', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 7, lastname: 'Andalib', firstname: 'Mr. Nice', email: 'acodd@yopmail.com', phoneNumber: 784126978 },
  { id: 8, lastname: 'Andaliba', firstname: 'Mr. Nicea', email: 'urrab@yopmail.com', phoneNumber: 7841269728 },
  { id: 9, lastname: 'Andalibx', firstname: 'Camille', email: 'orrip@yopmail.com', phoneNumber: 784126978 },
  { id: 10, lastname: 'Andalibaw', firstname: 'Naruto', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 11, lastname: 'Andalibad', firstname: 'Keltoum', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 12, lastname: 'Andalsad', firstname: 'Mr. Nice', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 13, lastname: 'Andalib', firstname: 'Mr. Nice', email: 'acodd@yopmail.com', phoneNumber: 784126978 },
  { id: 14, lastname: 'Andaliba', firstname: 'Mr. Nicea', email: 'urrab@yopmail.com', phoneNumber: 7841269728 },
  { id: 15, lastname: 'Andalibx', firstname: 'Camille', email: 'orrip@yopmail.com', phoneNumber: 784126978 },
  { id: 16, lastname: 'Andalibaw', firstname: 'Naruto', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 17, lastname: 'Andalibad', firstname: 'Keltoum', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 18, lastname: 'Andalsad', firstname: 'Mr. Nice', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 19, lastname: 'Andalib', firstname: 'Mr. Nice', email: 'acodd@yopmail.com', phoneNumber: 784126978 },
  { id: 20, lastname: 'Andaliba', firstname: 'Mr. Nicea', email: 'urrab@yopmail.com', phoneNumber: 7841269728 },
  { id: 21, lastname: 'Andalibx', firstname: 'Camille', email: 'orrip@yopmail.com', phoneNumber: 784126978 },
  { id: 22, lastname: 'Andalibaw', firstname: 'Naruto', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 23, lastname: 'Andalibad', firstname: 'Keltoum', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 24, lastname: 'Andalsad', firstname: 'Mr. Nice', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 25, lastname: 'Andalib', firstname: 'Mr. Nice', email: 'acodd@yopmail.com', phoneNumber: 784126978 },
  { id: 26, lastname: 'Andaliba', firstname: 'Mr. Nicea', email: 'urrab@yopmail.com', phoneNumber: 7841269728 },
  { id: 27, lastname: 'Andalibx', firstname: 'Camille', email: 'orrip@yopmail.com', phoneNumber: 784126978 },
  { id: 28, lastname: 'Andalibad', firstname: 'Keltoum', email: 'nani@gmail.com', phoneNumber: 784126978 },
  { id: 29, lastname: 'milouda', firstname: 'Mr. Nice', email: 'nani@gmail.com', phoneNumber: 784126978 }
];
